# Generated by Django 5.2.8 on 2025-12-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studends',
            new_name='Students',
        ),
    ]
